### ISSUE TITLE
google doesn't accept nonce

### ISSUE THREAD

**Issue by aaronchi** [jjbohn/omniauth-openid-connect#7]
When trying to login via google:

Error: invalid_request
Parameter not allowed for this message type: nonce

Seems like nonce should be removed or at least made optional via config

**Comment by gaelian** [comment]
Hello,

Sorry to bring up an old issue here, but I'm trying to get omniauth-openid-connect to work with Google and am having some issues, bit of an OpenID Connect n00b here, hoping for a little help.

I'm using omniauth-openid-connect at the latest commit (b9246a04bc0b6efbcf0130ef4e12051c860c3e28).

My initializers/omniauth.rb file currently looks like this:

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
	provider :openid_connect,
	name: :google,
	scope: [:openid, :email, :profile, :address],
	response_type: :code,
    send_nonce: false,
    issuer: "https://accounts.google.com",
    client_auth_method: :query,
    client_options: {
      port: 443,
      scheme: "https",
      host: "accounts.google.com",
      identifier: "MY_ID",
      secret: "MY_SECRET",
      redirect_uri: "http://localhost:3000/auth/google/callback",
      authorization_endpoint: "/o/oauth2/auth",
      token_endpoint: "/o/oauth2/token",
      userinfo_endpoint: "https://www.googleapis.com/plus/v1/people/me/openIdConnect"
    }
end
```

When I initiate the auth request, I get to Google's consent screen OK (the screen where it says "My App would like to" etc.), I then click the "Accept" button and I get the error `JSON::JWS::VerificationFailed`. By the stack trace I can see that I get to the [`decode_id_token`](https://github.com/jjbohn/omniauth-openid-connect/blob/master/lib/omniauth/strategies/openid_connect.rb#L170) method, and then things start go wrong once omniauth-openid-connect passes off to `::OpenIDConnect::ResponseObject::IdToken.decode`:

```ruby
def decode_id_token(id_token)
    ::OpenIDConnect::ResponseObject::IdToken.decode(id_token, public_key)
end
```

I seem to be getting an `id_token` value back from Google OK but I've noticed that the `public_key` method is returning `nil` for me and I'm wondering if this has something to do with my problem. Can anyone provide some insight into what I need to do differently here in order to get things working?

I've tried adding `discovery: true` and/or `jwks_uri: "https://www.googleapis.com/oauth2/v2/certs"` in my onmiauth.rb, but neither seems to make a difference. Would I be correct in assuming that discovery is not necessary if options are being set manually?

**Comment by jjbohn** [comment]
Yeah, discovery shouldn't be necessary. I'm not sure about your issue though. The error is getting raised [here](https://github.com/nov/json-jwt/blob/97fa2e954ab4db0b8d7cb4c58539096548bcbb0a/lib/json/jws.rb#L19-L22). And [here's](https://github.com/nov/json-jwt/blob/97fa2e954ab4db0b8d7cb4c58539096548bcbb0a/lib/json/jws.rb#L68-L79) what can make that error come up. Do you options match [this](https://accounts.google.com/.well-known/openid-configuration)?

**Comment by nbibler** [comment]
I don't see that Google openly supports the `address` scope requested. I'm not sure if that is the cause of the issue, but according to their [discoverable configuration](https://accounts.google.com/.well-known/openid-configuration), there is no `address` scope option:

```javascript
scopes_supported: [
"openid",
"email",
"profile"
]
```

Also, it looks as though their preferred userinfo endpoint has changed (again, from the discoverable configuration link above):

```
userinfo_endpoint: "https://www.googleapis.com/oauth2/v3/userinfo",
```

**Comment by gaelian** [comment]
Thanks for the input guys. Taking into account this further info, I've given it one last good go here, but I can't get past the `JSON::JWS::VerificationFailed` error. My best guess is still that it has something to do with the `public_key` method returning `nil` and I don't know what config to provide in order to get the required value.

In any case, I've gone with the [omniauth-google-oauth2](https://github.com/zquestz/omniauth-google-oauth2) strategy for now (thanks for the suggestion @nbibler). I guess this option is less flexible if one wants to use providers other than Google but that it works with minimal config is enough for me at present, and one can always add other strategies later.

**Comment by machisuji** [comment]
I know it's an old issue and this is not even active anymore but just for googler's sake here goes the resolution.

The omniauth-google-oauth2 decodes the ID Token without verifying the signature.
That's why it works and omniauth-openid-connect doesn't. For this to work in omniauth-openid-connect you have to provide the necessary options to get the public key as you correctly assumed.

In the case of google this would be achieved through the following options:

```
client_signing_alg: :RS256
client_jwk_signing_key: '{ "keys": [ { "e": "AQAB", "use": "sig", "kty": "RSA", "alg": "RS256", ... }, ... ] }'
```

Where they key is coming from https://www.googleapis.com/oauth2/v3/certs.
With these options set the ID token is decoded and can be verified.

Using discovery with the `jwks_uri ` endpoint set would also fix this issue presumably.

If you use `:skip_verification` as the public key parameter the decoding works as well.
